name: Changelog
on:
  issues:
    types:
      - closed

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Dump Github Context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - uses: patrickpedersen/autoChangelog@main
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        latest_changes_header: '### Latest Changes - Latest Changes 🤷'
