name: Docker Deploy

on:
  push:
    branches:
      - main
  release:
    types:
      - published

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            patrickpedersen/autochangelog:latest
            ghcr.io/patrickpedersen/autochangelog:latest
      - name: Build and push tag
        if: github.event_name == 'release'
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            patrickpedersen/autoChangelog:${{ github.event.release.tag_name }}
            ghcr.io/patrickpedersen/autoChangelog:${{ github.event.release.tag_name }}
